# Site settings
title: 28*Circle 
email: intercept.x.attack@gmail.com
description: "28*Circle is a bilingual (English and Japanese) activity group/circle located in Toronto."
baseurl: "http://28circle.info"
url: ""
subtitle: "日本語・英語サークル"
keywords: ""
simple_search: http://google.com/search
# Build settings
markdown: kramdown
author: none
permalink: "/:year/:month/:day/:title/"
paginate: 7
paginate_path: "/page/:num/"
